#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Temporal-window ablation for single-plant LAI estimation.

This script evaluates whether single-month or combined-month feature sets provide
better LAI estimation performance. It follows the manuscript logic: candidate
features are ranked by their absolute Pearson correlation with observed LAI
within each temporal window, the top-K features are used as model inputs, and a
baseline model is evaluated by leave-one-out cross-validation (LOOCV).

Required input
--------------
A feature table generated by 02_extract_vi_texture_features.py. Required columns:
    Date, LAI_Observed, and candidate feature columns.
Optional columns:
    Tree_ID or ID.

Outputs
-------
- temporal_window_ablation_metrics.csv
- temporal_window_ablation_predictions.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.model_selection import LeaveOneOut, cross_val_predict
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error


DEFAULT_INPUT = "outputs/features/single_plant_lai_features.csv"
DEFAULT_OUTPUT_DIR = "outputs/temporal_ablation"

VI_24 = [
    "NDVI", "RVI", "DVI", "TNDVI", "RDVI", "NGRDI", "RI", "MSR", "MSAVI", "TVI",
    "WDRVI", "GRVI", "NLI", "MTVI2", "CRI", "GNDVI", "OSAVI", "SAVI", "PVI",
    "MCARI", "RGRI", "NDRE", "TCARI_OSAVI", "RECI",
]

TEX_8 = [
    "TexNIR_Contrast_Avg", "TexNIR_Dissimilarity_Avg", "TexNIR_Homogeneity_Avg",
    "TexNIR_Energy_Avg", "TexNIR_Correlation_Avg", "TexNIR_ASM_Avg",
    "TexNIR_Entropy_Avg", "TexNIR_Mean_Avg",
]


def read_table(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if path.suffix.lower() in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    return pd.read_csv(path)


def infer_stage(date_value) -> str:
    """Map a date string to May, Aug, Sep, or Other."""
    text = str(date_value).replace("/", "-").lower()
    if "may" in text or "05-28" in text or "5-28" in text or "2024-05" in text:
        return "May"
    if "aug" in text or "08-07" in text or "8-7" in text or "2024-08" in text or "2024-8" in text:
        return "Aug"
    if "sep" in text or "09-28" in text or "9-28" in text or "2024-09" in text or "2024-9" in text:
        return "Sep"
    return "Other"


def metrics(y_true: np.ndarray, y_pred: np.ndarray) -> Dict[str, float]:
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    return {
        "R2": float(r2_score(y_true, y_pred)),
        "RMSE": rmse,
        "MAE": float(mean_absolute_error(y_true, y_pred)),
        "RPD": float(np.std(y_true, ddof=1) / rmse) if rmse > 0 and len(y_true) > 1 else np.nan,
    }


def build_feature_pool(df: pd.DataFrame, include_bands: bool = False, include_texture: bool = True) -> List[str]:
    features: List[str] = []
    features.extend([c for c in VI_24 if c in df.columns])
    if include_bands:
        features.extend([c for c in ["Green_Refl", "Red_Refl", "RedEdge_Refl", "NIR_Refl",
                                    "Green_Std", "Red_Std", "RedEdge_Std", "NIR_Std"] if c in df.columns])
    if include_texture:
        # Prefer the manuscript-ready 8 averaged texture columns, but keep any TexNIR columns if needed.
        tex_cols = [c for c in TEX_8 if c in df.columns]
        if not tex_cols:
            tex_cols = [c for c in df.columns if str(c).startswith("TexNIR_")]
        features.extend(tex_cols)
    return list(dict.fromkeys(features))


def select_top_k_by_correlation(df: pd.DataFrame, features: List[str], target: str, k: int) -> List[str]:
    valid = []
    for f in features:
        if f not in df.columns:
            continue
        x = pd.to_numeric(df[f], errors="coerce")
        y = pd.to_numeric(df[target], errors="coerce")
        mask = x.notna() & y.notna()
        if mask.sum() < 5 or x[mask].nunique() <= 1:
            continue
        corr = np.corrcoef(x[mask], y[mask])[0, 1]
        if np.isfinite(corr):
            valid.append((f, abs(float(corr))))
    valid = sorted(valid, key=lambda t: t[1], reverse=True)
    return [f for f, _ in valid[: min(k, len(valid))]]


def evaluate_window(df: pd.DataFrame, stages: List[str], name: str, features: List[str], top_k: int, model_name: str):
    sub = df[df["Stage"].isin(stages)].copy()
    sub = sub.replace([np.inf, -np.inf], np.nan)
    selected = select_top_k_by_correlation(sub, features, "LAI_Observed", top_k)
    sub = sub.dropna(subset=selected + ["LAI_Observed"])
    if len(sub) < 10 or not selected:
        return None, pd.DataFrame()

    X = sub[selected].to_numpy(dtype=float)
    y = sub["LAI_Observed"].to_numpy(dtype=float)

    if model_name.lower() == "randomforest":
        model = RandomForestRegressor(n_estimators=300, random_state=42, n_jobs=-1)
    else:
        model = GradientBoostingRegressor(random_state=42)

    loo = LeaveOneOut()
    y_pred = cross_val_predict(model, X, y, cv=loo, n_jobs=-1)
    m = metrics(y, y_pred)
    row = {
        "Temporal_Window": name,
        "Stages": "+".join(stages),
        "Sample_Size": int(len(y)),
        "Num_Features": int(len(selected)),
        "Selected_Features": ";".join(selected),
        **m,
    }

    pred_df = pd.DataFrame({
        "Temporal_Window": name,
        "Tree_ID": sub.get("Tree_ID", sub.get("ID", pd.Series(np.arange(len(sub))))).values,
        "Date": sub["Date"].values,
        "Observed_LAI": y,
        "Predicted_LAI": y_pred,
        "Residual": y - y_pred,
    })
    return row, pred_df


def run_temporal_ablation(input_file: str, output_dir: str, top_k: int, model_name: str,
                          include_bands: bool, include_texture: bool) -> None:
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    df = read_table(input_file)
    if "Date" not in df.columns or "LAI_Observed" not in df.columns:
        raise ValueError("Input table must contain Date and LAI_Observed columns.")
    df["Stage"] = df["Date"].apply(infer_stage)

    features = build_feature_pool(df, include_bands=include_bands, include_texture=include_texture)
    if not features:
        raise ValueError("No candidate features were found in the input table.")

    windows = [
        (["May"], "May Only"),
        (["Aug"], "Aug Only"),
        (["Sep"], "Sep Only"),
        (["May", "Aug"], "May + Aug"),
        (["May", "Sep"], "May + Sep"),
        (["Aug", "Sep"], "Aug + Sep"),
        (["May", "Aug", "Sep"], "Full Time-series"),
    ]

    rows = []
    preds = []
    for stages, name in windows:
        row, pred = evaluate_window(df, stages, name, features, top_k, model_name)
        if row is not None:
            rows.append(row)
            preds.append(pred)
            print(f"{name:18s} | N={row['Sample_Size']:3d} | R2={row['R2']:.3f} | RMSE={row['RMSE']:.3f}")

    pd.DataFrame(rows).to_csv(out_dir / "temporal_window_ablation_metrics.csv", index=False, encoding="utf-8-sig")
    if preds:
        pd.concat(preds, ignore_index=True).to_csv(out_dir / "temporal_window_ablation_predictions.csv", index=False, encoding="utf-8-sig")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Temporal-window ablation for LAI estimation.")
    parser.add_argument("--input", default=DEFAULT_INPUT, help="Feature table from 02_extract_vi_texture_features.py.")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR, help="Directory for output tables.")
    parser.add_argument("--top-k", type=int, default=15, help="Number of top correlation-ranked features per window.")
    parser.add_argument("--model", choices=["GBDT", "RandomForest"], default="GBDT", help="Baseline model.")
    parser.add_argument("--include-bands", action="store_true", help="Include base reflectance and standard-deviation features.")
    parser.add_argument("--no-texture", action="store_true", help="Exclude texture features from candidate pool.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    run_temporal_ablation(
        input_file=args.input,
        output_dir=args.output_dir,
        top_k=args.top_k,
        model_name=args.model,
        include_bands=args.include_bands,
        include_texture=not args.no_texture,
    )


if __name__ == "__main__":
    main()
