#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Orchard-scale LAI mapping from UAV multispectral orthomosaics.

This script trains or loads a GBDT LAI model, computes raster vegetation-index
and approximate NIR texture layers, and writes a predicted LAI GeoTIFF for a
specified image date.

Required inputs
---------------
1) Feature table used for training, generated by 02_extract_vi_texture_features.py.
2) Selected-feature text file, one feature name per line. The features should be
   computable from the raster image, e.g. vegetation indices and TexNIR_*_Avg.
3) Imagery configuration CSV with columns Date, Green, Red, RedEdge, NIR and
   optional calibration coefficients Green_a, Green_b, ..., NIR_a, NIR_b.

Important note
--------------
The pixel-wise texture calculation here is an efficient moving-window
approximation designed for wall-to-wall mapping. The sample-level feature table
uses GLCM statistics within each dynamic ROI. This distinction should be stated
when the full mapping product is used as a visualization/application step.

Outputs
-------
- LAI_map_<date>.tif
- trained_gbdt_model.joblib and trained_scaler.joblib if --model-dir is used
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import joblib
import numpy as np
import pandas as pd
import rasterio
from rasterio.enums import Resampling
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from scipy import ndimage as ndi


DEFAULT_FEATURE_TABLE = "outputs/features/single_plant_lai_features.csv"
DEFAULT_FEATURE_LIST = "outputs/feature_selection/selected_features_topK.txt"
DEFAULT_IMAGERY_CONFIG = "example_imagery_config.csv"
DEFAULT_OUTPUT_DIR = "outputs/lai_mapping"


def read_table(path: str | Path) -> pd.DataFrame:
    path = Path(path)
    if path.suffix.lower() in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    return pd.read_csv(path)


def load_selected_features(path: str | Path) -> List[str]:
    features = [line.strip() for line in Path(path).read_text(encoding="utf-8").splitlines() if line.strip()]
    if not features:
        raise ValueError(f"No features found in {path}")
    return features


def train_or_load_model(feature_table: str, selected_features: List[str], model_dir: str | Path,
                        force_retrain: bool = False):
    model_dir = Path(model_dir)
    model_dir.mkdir(parents=True, exist_ok=True)
    model_path = model_dir / "trained_gbdt_model.joblib"
    scaler_path = model_dir / "trained_scaler.joblib"

    if model_path.exists() and scaler_path.exists() and not force_retrain:
        return joblib.load(model_path), joblib.load(scaler_path)

    df = read_table(feature_table).replace([np.inf, -np.inf], np.nan)
    if "Status" in df.columns:
        df = df[df["Status"].astype(str).str.lower().eq("success")].copy()
    missing = [f for f in selected_features if f not in df.columns]
    if missing:
        raise ValueError(f"Training feature table is missing selected features: {missing}")
    df = df.dropna(subset=selected_features + ["LAI_Observed"]).copy()
    if len(df) < 20:
        raise ValueError("Too few training samples after dropping missing values.")

    X = df[selected_features].to_numpy(dtype=float)
    y = df["LAI_Observed"].to_numpy(dtype=float)
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    model = GradientBoostingRegressor(
        random_state=42,
        n_estimators=600,
        learning_rate=0.01,
        max_depth=3,
        subsample=0.6,
    )
    model.fit(X_scaled, y)
    joblib.dump(model, model_path)
    joblib.dump(scaler, scaler_path)
    return model, scaler


def read_band(path: str | Path, out_shape: Optional[Tuple[int, int]] = None):
    with rasterio.open(path) as src:
        if out_shape is None:
            arr = src.read(1).astype(np.float32)
            profile = src.profile.copy()
        else:
            arr = src.read(1, out_shape=out_shape, resampling=Resampling.average).astype(np.float32)
            scale_x = src.width / out_shape[1]
            scale_y = src.height / out_shape[0]
            transform = src.transform * src.transform.scale(scale_x, scale_y)
            profile = src.profile.copy()
            profile.update({"height": out_shape[0], "width": out_shape[1], "transform": transform})
    return arr, profile


def get_image_paths(config_file: str, date: str) -> Tuple[pd.Series, Dict[str, Tuple[float, float]]]:
    cfg = pd.read_csv(config_file)
    if "Date" not in cfg.columns:
        raise ValueError("Imagery config must contain Date column.")
    match = cfg[cfg["Date"].astype(str) == str(date)]
    if match.empty:
        raise ValueError(f"Date {date} not found in imagery config.")
    row = match.iloc[0]
    coeffs = {}
    for b in ["Green", "Red", "RedEdge", "NIR"]:
        a = row.get(f"{b}_a", np.nan)
        bb = row.get(f"{b}_b", np.nan)
        if pd.isna(a) or pd.isna(bb):
            coeffs[b] = (1.0, 0.0)
        else:
            coeffs[b] = (float(a), float(bb))
    return row, coeffs


def minmax01(a: np.ndarray, mask: np.ndarray) -> np.ndarray:
    v = a[mask & np.isfinite(a)]
    if v.size == 0:
        return np.zeros_like(a, dtype=np.float32)
    lo, hi = np.percentile(v, [2, 98])
    out = (np.clip(a, lo, hi) - lo) / (hi - lo + 1e-6)
    return np.clip(out, 0, 1).astype(np.float32)


def majority_filter(mask: np.ndarray, size: int = 3, keep_if_ge: int = 5) -> np.ndarray:
    kernel = np.ones((size, size), dtype=np.uint8)
    count = ndi.convolve(mask.astype(np.uint8), kernel, mode="nearest")
    return count >= keep_if_ge


def calculate_vi_layers(G: np.ndarray, R: np.ndarray, RE: np.ndarray, N: np.ndarray) -> Dict[str, np.ndarray]:
    eps = 1e-6
    G, R, RE, N = G + eps, R + eps, RE + eps, N + eps
    out = {}
    out["NDVI"] = (N - R) / (N + R)
    out["RVI"] = N / R
    out["DVI"] = N - R
    out["TNDVI"] = np.sqrt(np.clip(out["NDVI"] + 0.5, 0, None))
    out["RDVI"] = (N - R) / np.sqrt(np.clip(N + R, eps, None))
    out["NGRDI"] = (G - R) / (G + R)
    out["RI"] = (R - G) / (R + G)
    sr = N / R
    out["MSR"] = (sr - 1) / np.sqrt(np.clip(sr + 1, eps, None))
    out["MSAVI"] = (2 * N + 1 - np.sqrt(np.clip((2 * N + 1) ** 2 - 8 * (N - R), eps, None))) / 2
    out["TVI"] = 0.5 * (120 * (RE - G) - 200 * (R - G))
    out["WDRVI"] = (0.1 * N - R) / (0.1 * N + R)
    out["GRVI"] = G / R
    out["NLI"] = (N ** 2 - R) / (N ** 2 + R)
    out["MTVI2"] = (1.5 * (1.2 * (N - G) - 2.5 * (R - G))) / np.sqrt(
        np.clip((2 * N + 1) ** 2 - (6 * N - 5 * np.sqrt(np.clip(R, 0, None))) - 0.5, eps, None)
    )
    out["CRI"] = (1 / G) - (1 / RE)
    out["GNDVI"] = (N - G) / (N + G)
    out["OSAVI"] = (N - R) / (N + R + 0.16)
    out["SAVI"] = ((N - R) / (N + R + 0.5)) * 1.5
    out["PVI"] = (N - R) / np.sqrt(2)
    out["MCARI"] = ((RE - R) - 0.2 * (RE - G)) * (RE / R)
    out["RGRI"] = R / G
    out["NDRE"] = (N - RE) / (N + RE)
    out["TCARI_OSAVI"] = (3 * ((RE - R) - 0.2 * (RE - G) * (RE / R))) / (out["OSAVI"] + eps)
    out["RECI"] = (N / RE) - 1
    return out


def calculate_fast_texture_layers(N: np.ndarray, window: int = 9) -> Dict[str, np.ndarray]:
    """Moving-window approximations of the eight NIR texture features."""
    N_scaled = np.clip(N * 255.0, 0, 255)
    mean = ndi.uniform_filter(N_scaled, size=window)
    var = np.clip(ndi.uniform_filter(N_scaled ** 2, size=window) - mean ** 2, 0, None)
    shift_x = np.roll(N_scaled, shift=1, axis=1)
    shift_y = np.roll(N_scaled, shift=1, axis=0)
    diff = (np.abs(N_scaled - shift_x) + np.abs(N_scaled - shift_y)) / 2.0
    contrast = ndi.uniform_filter(diff ** 2, size=window)
    dissimilarity = ndi.uniform_filter(diff, size=window)
    homogeneity = ndi.uniform_filter(1.0 / (1.0 + diff ** 2), size=window)
    energy = 1.0 / (1.0 + var + 1e-6)
    asm = energy ** 2
    entropy = -np.log(var + 1e-6)
    correlation = homogeneity
    return {
        "TexNIR_Mean_Avg": mean,
        "TexNIR_Contrast_Avg": contrast,
        "TexNIR_Dissimilarity_Avg": dissimilarity,
        "TexNIR_Homogeneity_Avg": homogeneity,
        "TexNIR_Energy_Avg": energy,
        "TexNIR_Correlation_Avg": correlation,
        "TexNIR_ASM_Avg": asm,
        "TexNIR_Entropy_Avg": entropy,
    }


def run_mapping(feature_table: str, feature_list: str, imagery_config: str, date: str, output_dir: str,
                model_dir: Optional[str], force_retrain: bool, downsample: int, texture_window: int,
                nonveg_lai: float) -> None:
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if model_dir is None:
        model_dir = str(out_dir / "model")

    selected_features = load_selected_features(feature_list)
    model, scaler = train_or_load_model(feature_table, selected_features, model_dir, force_retrain=force_retrain)

    cfg_row, coeffs = get_image_paths(imagery_config, date)
    with rasterio.open(cfg_row["Green"]) as ref:
        H, W = ref.height, ref.width
    out_shape = (H // downsample, W // downsample) if downsample and downsample > 1 else None

    G_dn, profile = read_band(cfg_row["Green"], out_shape=out_shape)
    R_dn, _ = read_band(cfg_row["Red"], out_shape=out_shape)
    RE_dn, _ = read_band(cfg_row["RedEdge"], out_shape=out_shape)
    N_dn, _ = read_band(cfg_row["NIR"], out_shape=out_shape)

    valid = np.isfinite(G_dn) & np.isfinite(R_dn) & np.isfinite(RE_dn) & np.isfinite(N_dn) & (G_dn > 0) & (R_dn > 0) & (N_dn > 0)
    Gm, Rm, REm, Nm = minmax01(G_dn, valid), minmax01(R_dn, valid), minmax01(RE_dn, valid), minmax01(N_dn, valid)
    ndvi_norm = (Nm - Rm) / (Nm + Rm + 1e-6)
    brightness = (Gm + Rm + REm) / 3.0
    nr_ratio = Nm / (Rm + 1e-6)
    nonveg_raw = valid & ((ndvi_norm < 0.18) | ((brightness > 0.28) & (nr_ratio < 1.70)))
    nonveg = majority_filter(nonveg_raw, size=3, keep_if_ge=5) & valid
    veg = valid & (~nonveg)

    G = np.clip(G_dn * coeffs["Green"][0] + coeffs["Green"][1], 1e-4, 1.0)
    R = np.clip(R_dn * coeffs["Red"][0] + coeffs["Red"][1], 1e-4, 1.0)
    RE = np.clip(RE_dn * coeffs["RedEdge"][0] + coeffs["RedEdge"][1], 1e-4, 1.0)
    N = np.clip(N_dn * coeffs["NIR"][0] + coeffs["NIR"][1], 1e-4, 1.0)

    layers = calculate_vi_layers(G, R, RE, N)
    layers.update(calculate_fast_texture_layers(N, window=texture_window))
    for band_name, arr in [("Green_Refl", G), ("Red_Refl", R), ("RedEdge_Refl", RE), ("NIR_Refl", N)]:
        layers[band_name] = arr

    missing = [f for f in selected_features if f not in layers]
    if missing:
        raise ValueError(f"Selected features cannot be generated from image layers: {missing}")

    X = np.zeros((int(veg.sum()), len(selected_features)), dtype=np.float32)
    for i, f in enumerate(selected_features):
        X[:, i] = layers[f][veg]
    X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

    preds = model.predict(scaler.transform(X))
    preds = np.clip(preds, 0.0, 8.0)
    lai = np.full(G.shape, np.nan, dtype=np.float32)
    lai[veg] = preds.astype(np.float32)
    lai[nonveg] = np.float32(nonveg_lai)

    profile.update({"count": 1, "dtype": "float32", "compress": "lzw", "nodata": np.nan})
    safe_date = str(date).replace("/", "-").replace(" ", "_")
    out_path = out_dir / f"LAI_map_{safe_date}.tif"
    with rasterio.open(out_path, "w", **profile) as dst:
        dst.write(lai, 1)
    print(f"Saved LAI map: {out_path}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train/load GBDT and produce orchard-scale LAI map.")
    parser.add_argument("--feature-table", default=DEFAULT_FEATURE_TABLE, help="Training feature table.")
    parser.add_argument("--features", default=DEFAULT_FEATURE_LIST, help="Selected-feature text file.")
    parser.add_argument("--imagery-config", default=DEFAULT_IMAGERY_CONFIG, help="Imagery configuration CSV.")
    parser.add_argument("--date", required=True, help="Image date to map; must match Date in imagery config.")
    parser.add_argument("--output-dir", default=DEFAULT_OUTPUT_DIR, help="Output directory.")
    parser.add_argument("--model-dir", default=None, help="Directory for saved model/scaler. Defaults to output_dir/model.")
    parser.add_argument("--force-retrain", action="store_true", help="Retrain even if saved model exists.")
    parser.add_argument("--downsample", type=int, default=2, help="Downsampling factor for faster mapping. Use 1 for full resolution.")
    parser.add_argument("--texture-window", type=int, default=9, help="Moving-window size for texture approximation.")
    parser.add_argument("--nonveg-lai", type=float, default=0.15, help="Value assigned to non-vegetation pixels.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    run_mapping(
        feature_table=args.feature_table,
        feature_list=args.features,
        imagery_config=args.imagery_config,
        date=args.date,
        output_dir=args.output_dir,
        model_dir=args.model_dir,
        force_retrain=args.force_retrain,
        downsample=args.downsample,
        texture_window=args.texture_window,
        nonveg_lai=args.nonveg_lai,
    )


if __name__ == "__main__":
    main()
